import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/Components/nav";
import LandingPageMain from "@/Components/LandingPageMain";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Was not really sure where to place my (jeffery's) code so i just put it here!, it containes the header and the landing page component */}
      <main>
        {" "}
        <Nav />
        <div className="landingbody">
          <LandingPageMain />
        </div>
      </main>
    </>
  );
}
